import {
  Anchor,
  Bath,
  Bed,
  Building,
  Building2,
  Car,
  ChefHat,
  Flame,
  Home,
  Palmtree,
  Sailboat,
  Snowflake,
  Sofa,
  Sprout,
  Sunset,
  Trees,
  Tv,
  Users,
  UtensilsCrossed,
  Waves,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  snowflake: Snowflake,
  tv: Tv,
  chefHat: ChefHat,
  sprout: Sprout,
  car: Car,
  flame: Flame,
  users: Users,
  trees: Trees,
  sailboat: Sailboat,
  waves: Waves,
  anchor: Anchor,
  home: Home,
  building: Building,
  building2: Building2,
  sofa: Sofa,
  bed: Bed,
  utensils: UtensilsCrossed,
  bath: Bath,
  palmtree: Palmtree,
  sunset: Sunset,
};
